services:
  dev: 
    build:
      context: .
      dockerfile: docker/tf.Dockerfile
    image: git.uwaterloo.ca:5050/watonomous/registry/uwarg/cv-bootcamp

    ipc: host
    tty: true

    volumes:
      - ./src:/root/src

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]