epochs: 50
out_dir: output
exp_name: moreaugrepro_nozoom_16batch

data:
  train_split: "train"
  val_split: "test"
  shuffle: 1000
  batch_size: 16
  repeat: 5
  random_flip: horizontal_and_vertical
  random_rotation: 0.5
  # random_zoom: 0.5

model:
  # at least 1
  num_cnn_layers: 4
  num_cnn_filters: 512
  cnn_kernel_size: 3

  # at least 1
  num_dense_layers: 4
  dense_layer_width: 4096

  dropout: 0.2

train:
  optimizer: adam
  metrics: ["accuracy"]