#! /usr/bin/python2.7

# generate superlong testcase

from random import randint
a = []
i = 0
while i < 2147483:
    a.append(randint(-2147483648,2147483647))
    i = i + 1

f = open("Superlong.in","w")
f.write(str(len(a))+'\n')
for i in a:
    f.write(str(i)+'\n')
a.sort()
e = open("Superlong.exp","w")
for i in a:
    e.write(str(i)+'\n')
