#! /usr/bin/python2.7

infile_name = raw_input('>> input file name:')
outfile_name = raw_input('>> output file name:')

lst = []

while True:
    try:
        num = int(raw_input())
        lst.append(num)
    except:
        break

infile = open(infile_name,'w')
infile.write(str(len(lst)))
infile.write('\n')
for i in lst:
    infile.write(str(i)+'\n')
lst.sort()
outfile = open(outfile_name, 'w')
for i in lst:
    outfile.write(str(i)+'\n')
